'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import {
  Analytics,
  ConfigList,
  adminGet,
  formatPoints,
} from '../../lib/admin';
import { useSession } from '../../lib/queries';
import { hasCapability } from '../../lib/capabilities';
import { AdminAccessGate } from '../../components/admin/admin-access-gate';

type ProviderStatus = {
  provider: { configured: boolean; lastErrorCode: string | null; consecutiveFailures: number };
  settlementWorker: { enabled: boolean; lastStatus: string | null };
  cache: { healthy: boolean };
};

type StaleBets = { bets: { betId: string }[] };

/**
 * Administrator control centre.
 *
 * Every figure here is aggregated by the backend; the browser never receives
 * raw rounds to total up. Nothing on this page can influence a result - the
 * operator surface is configuration and observation only.
 */
export default function AdminOverview() {
  const [config, setConfig] = useState<ConfigList | null>(null);
  const [analytics, setAnalytics] = useState<Analytics | null>(null);
  const [providers, setProviders] = useState<ProviderStatus | null>(null);
  const [stale, setStale] = useState<StaleBets | null>(null);
  const [users, setUsers] = useState<number | null>(null);
  const [unreadSecurity, setUnreadSecurity] = useState<number | null>(null);
  const [mfa, setMfa] = useState<{ enabled: boolean } | null>(null);
  const [state, setState] = useState<'loading' | 'ready' | 'denied'>('loading');
  const session = useSession();
  const router = useRouter();
  const platformManager = hasCapability(session.data?.role, 'PLATFORM_MANAGE');

  const load = useCallback(async () => {
    adminGet<{ enabled: boolean }>('/auth/2fa/status').then(setMfa);
    const [configs, stats, userList, security] = await Promise.all([
      adminGet<ConfigList>('/admin/casino/config'),
      adminGet<Analytics>('/admin/casino/analytics?period=ALL'),
      adminGet<{ id: string }[]>('/admin/users?limit=100'),
      adminGet<{ unread: number }>('/admin/security/events?limit=1&unread=true'),
    ]);
    // Platform/provider state is PLATFORM_MANAGE: only request it when allowed,
    // so an ADMIN overview never bundles a 403.
    const [status, staleBets] = platformManager
      ? await Promise.all([
          adminGet<ProviderStatus>('/admin/sports/providers/status'),
          adminGet<StaleBets>('/admin/sports/bets/stale?limit=100'),
        ])
      : [null, null];
    if (!configs || !stats) {
      setState('denied');
      return;
    }
    setConfig(configs);
    setAnalytics(stats);
    setProviders(status);
    setStale(staleBets);
    setUsers(userList?.length ?? null);
    setUnreadSecurity(security?.unread ?? null);
    setState('ready');
  }, [platformManager]);

  useEffect(() => {
    // A manager has no game overview: their work is the people page.
    if (session.data?.role === 'MANAGER') { router.replace('/admin/users'); return; }
    void load();
  }, [load, router, session.data?.role]);

  if (state === 'denied') return <AdminAccessGate area="The control centre" />;

  const totals = analytics?.totals;
  const disabled = config?.games.filter((game) => !game.enabled).length ?? 0;
  const inMaintenance = config?.games.filter((game) => game.maintenance).length ?? 0;

  return (
    <main className="ops-page">
      <header className="ops-header">
        <div>
          <Link className="brand" href="/">FOOL&apos;S GOLD</Link>
          <span className="ops-divider">/</span>
          <span>Admin</span>
        </div>
        <nav>
          <Link href="/admin/casino/config">Game configuration</Link>
          <Link href="/admin/casino/math">Game math control</Link>
          <Link href="/admin/users">Users</Link>
          <Link href="/admin/security">Security</Link>
          {platformManager && <Link href="/admin/sports">Sports operations</Link>}
          <Link href="/admin/audit">Audit</Link>
        </nav>
      </header>

      <div className="ops-content">
        <section className="ops-hero">
          <div>
            <p className="ops-kicker">CONTROL CENTRE</p>
            <h1>Overview</h1>
            <p>
              Configuration applies to new rounds only. Results are generated by the
              server and cannot be chosen from here.
            </p>
          </div>
          <div className="ops-refresh">
            <button onClick={() => void load()} disabled={state === 'loading'}>
              {state === 'loading' ? 'Loading…' : 'Refresh'}
            </button>
          </div>
        </section>

        {state === 'loading' && <p className="state">Loading…</p>}

        {state === 'ready' && (
          <>
            {mfa?.enabled === false && (
              <p className="ops-alert ops-alert-action">
                Protect this account with Google Authenticator.{' '}
                <Link className="ops-link" href="/admin/two-factor">Turn it on</Link>
              </p>
            )}

            <section className="ops-section">
              <div className="ops-section-heading">
                <h2>What do you want to do?</h2>
                <span>
                  You are signed in as {session.data?.role === 'SUPER_ADMIN' ? 'a super administrator (you see everything)' : 'an administrator (you see only your own players)'}.
                </span>
              </div>
              <div className="ops-card-grid">
                <GuideLink href="/admin/users" title="Players and PTS" text="Create a player, add or remove PTS, set a password." />
                <GuideLink
                  href="/admin/security"
                  title="Security notifications"
                  text="See every PTS movement and big win. Check these often."
                  badge={unreadSecurity ? `${unreadSecurity} new` : undefined}
                />
                <GuideLink href="/admin/password" title="Change password" text="Set a new password for your own login." />
                <GuideLink href="/admin/two-factor" title="Google Authenticator" text="Protect your login with a code from your phone." badge={mfa?.enabled ? 'On' : 'Off'} />
                <GuideLink href="/admin/casino/math" title="Game return (RTP)" text="Choose how much each game pays back." />
                <GuideLink href="/admin/audit" title="Audit log" text="The full record of who did what." />
              </div>
            </section>

            <section className="ops-section">
              <div className="ops-section-heading"><h2>Platform</h2></div>
              <div className="ops-card-grid">
                <Card label="Users" value={formatPoints(users)} />
                <Card
                  label="Casino wagered"
                  value={formatPoints(totals?.totalWagered)}
                  note="virtual points"
                />
                <Card
                  label="Casino returned"
                  value={formatPoints(totals?.totalReturned)}
                  note="virtual points"
                />
                <Card
                  label="House result"
                  value={formatPoints(totals?.houseResult)}
                  note="wagered minus returned"
                  tone={Number(totals?.houseResult ?? 0) >= 0 ? undefined : 'warn'}
                />
                <Card
                  label="Observed RTP"
                  value={totals?.observedRtpPercent ? `${totals.observedRtpPercent}%` : '—'}
                  note="history, not a target"
                />
                <Card label="Active rounds" value={formatPoints(totals?.activeRounds)} />
              </div>
              <div className="ops-metrics">
                <span>Rounds <strong>{formatPoints(totals?.totalRounds)}</strong></span>
                <span>Wins <strong>{formatPoints(totals?.wins)}</strong></span>
                <span>Losses <strong>{formatPoints(totals?.losses)}</strong></span>
                {platformManager && <span>Stale sports bets <strong>{stale?.bets.length ?? 0}</strong></span>}
              </div>
            </section>

            <section className="ops-section">
              <div className="ops-section-heading">
                <h2>Availability</h2>
                <span><Link className="ops-link" href="/admin/casino/config">Configure</Link></span>
              </div>
              <div className="ops-card-grid">
                <Card
                  label="Casino"
                  value={config?.platform.casinoMaintenance ? 'Maintenance' : 'Open'}
                  tone={config?.platform.casinoMaintenance ? 'warn' : undefined}
                  text
                />
                <Card
                  label="Sportsbook"
                  value={config?.platform.sportsbookMaintenance ? 'Maintenance' : 'Open'}
                  tone={config?.platform.sportsbookMaintenance ? 'warn' : undefined}
                  text
                />
                <Card label="Games disabled" value={String(disabled)} tone={disabled ? 'warn' : undefined} />
                <Card label="Games in maintenance" value={String(inMaintenance)} tone={inMaintenance ? 'warn' : undefined} />
                {platformManager && (
                  <>
                    <Card
                      label="Sports provider"
                      value={providers?.provider.configured ? 'Configured' : 'Not configured'}
                      tone={providers?.provider.lastErrorCode ? 'bad' : undefined}
                      text
                    />
                    <Card
                      label="Cache"
                      value={providers?.cache.healthy ? 'Healthy' : 'Unavailable'}
                      tone={providers?.cache.healthy ? undefined : 'bad'}
                      text
                    />
                  </>
                )}
              </div>
            </section>

            <section className="ops-section">
              <div className="ops-section-heading">
                <h2>Per game</h2>
                <span>Theoretical is the configured maths; observed is history.</span>
              </div>
              <div className="ops-table-wrap">
                <table className="ops-table">
                  <thead>
                    <tr>
                      <th>Game</th><th>Config version</th><th>Theoretical</th>
                      <th>Observed</th><th>Rounds</th><th>Wagered</th>
                      <th>Returned</th><th>House</th>
                    </tr>
                  </thead>
                  <tbody>
                    {analytics?.games.length === 0 && (
                      <tr><td className="ops-empty" colSpan={8}>No rounds played yet.</td></tr>
                    )}
                    {analytics?.games.map((game) => (
                      <tr key={game.configVersion}>
                        <td>{game.gameType}</td>
                        <td><small>{game.configVersion}</small></td>
                        <td>{game.theoreticalRtpPercent ? `${game.theoreticalRtpPercent}%` : '—'}</td>
                        <td>{game.observedRtpPercent ? `${game.observedRtpPercent}%` : '—'}</td>
                        <td>{formatPoints(game.rounds)}</td>
                        <td>{formatPoints(game.totalWagered)}</td>
                        <td>{formatPoints(game.totalReturned)}</td>
                        <td>{formatPoints(game.houseResult)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <p className="ops-safe-note">{analytics?.note}</p>
            </section>
          </>
        )}
      </div>
    </main>
  );
}

function GuideLink({ href, title, text, badge }: { href: string; title: string; text: string; badge?: string }) {
  return (
    <Link className="ops-card" href={href}>
      <span>{badge ?? 'Open'}</span>
      <strong className="ops-card-text">{title}</strong>
      <small>{text}</small>
    </Link>
  );
}

function Card({ label, value, note, tone, text }: {
  label: string;
  value: string;
  note?: string;
  tone?: 'warn' | 'bad';
  text?: boolean;
}) {
  return (
    <div className={`ops-card ${tone ? `ops-card-${tone}` : ''}`}>
      <span>{label}</span>
      <strong className={text ? 'ops-card-text' : undefined}>{value}</strong>
      {note && <small>{note}</small>}
    </div>
  );
}
