import { BetLeg, Prisma } from '@prisma/client';
import { H2HSettlementEvaluator, SpreadSettlementEvaluator, TotalsSettlementEvaluator } from '../src/settlement/evaluators';
const leg = (data: Partial<BetLeg>) => ({ homeTeam: 'Home', awayTeam: 'Away', selectionName: 'Home', marketPoint: null, ...data } as BetLeg);
const result = (homeScore: number, awayScore: number) => ({ provider: 'fixture', providerEventId: 'event', status: 'FINAL' as const, homeScore, awayScore });
describe('pure market settlement evaluators', () => {
  it('settles H2H home, away and draw selections', () => { const evaluator = new H2HSettlementEvaluator(); expect(evaluator.evaluate(leg({ selectionName: 'Home' }), result(3, 1))).toBe('WON'); expect(evaluator.evaluate(leg({ selectionName: 'Away' }), result(3, 1))).toBe('LOST'); expect(evaluator.evaluate(leg({ selectionName: 'Draw' }), result(1, 1))).toBe('WON'); });
  it('settles totals and treats integer pushes as void', () => { const evaluator = new TotalsSettlementEvaluator(); expect(evaluator.evaluate(leg({ selectionName: 'Over', marketPoint: new Prisma.Decimal('2.5') }), result(2, 1))).toBe('WON'); expect(evaluator.evaluate(leg({ selectionName: 'Under', marketPoint: new Prisma.Decimal('2.5') }), result(2, 1))).toBe('LOST'); expect(evaluator.evaluate(leg({ selectionName: 'Over', marketPoint: new Prisma.Decimal('3') }), result(2, 1))).toBe('VOID'); });
  it('settles positive/negative spreads and pushes exactly', () => { const evaluator = new SpreadSettlementEvaluator(); expect(evaluator.evaluate(leg({ selectionName: 'Home', marketPoint: new Prisma.Decimal('-1.5') }), result(3, 1))).toBe('WON'); expect(evaluator.evaluate(leg({ selectionName: 'Away', marketPoint: new Prisma.Decimal('1.5') }), result(3, 1))).toBe('LOST'); expect(evaluator.evaluate(leg({ selectionName: 'Home', marketPoint: new Prisma.Decimal('-1') }), result(2, 1))).toBe('VOID'); });
  it('leaves partial results unresolved and voids cancelled events', () => { const evaluator = new H2HSettlementEvaluator(); expect(evaluator.evaluate(leg({}), { provider: 'fixture', providerEventId: 'event', status: 'UNKNOWN' })).toBe('UNRESOLVED'); expect(evaluator.evaluate(leg({}), { provider: 'fixture', providerEventId: 'event', status: 'CANCELLED' })).toBe('VOID'); });
});
