import { BetType, Prisma } from '@prisma/client';
import { PrismaService } from '../src/prisma.service';
import { NormalizedEventResult, SportsResultProvider } from '../src/settlement/result-provider';
import { SettlementService } from '../src/settlement/settlement.service';
import { uniqueTestEmail } from './test-identity';
describe('result ingestion and exactly-once settlement (PostgreSQL)', () => {
  const prisma = new PrismaService(); const provider: jest.Mocked<SportsResultProvider> = { getEventResult: jest.fn() }; const settlement = new SettlementService(prisma, provider); const userEmail = uniqueTestEmail('settlement'); let userId: string; let walletId: string;
  beforeAll(() => prisma.$connect()); afterAll(() => prisma.$disconnect());
  beforeEach(async () => { await prisma.$executeRawUnsafe('TRUNCATE TABLE "SportsEventResult", "LedgerEntry", "BetLeg", "Bet", "AuditLog", "RefreshToken", "Wallet", "User" CASCADE'); jest.clearAllMocks(); const user = await prisma.user.create({ data: { email: userEmail, passwordHash: 'x', wallet: { create: { balance: 900 } } }, include: { wallet: true } }); userId = user.id; walletId = user.wallet!.id; });
  const final = (eventId: string, homeScore: number, awayScore: number): NormalizedEventResult => ({ provider: 'fixture', providerEventId: eventId, status: 'FINAL', homeScore, awayScore, completedAt: new Date() });
  async function createBet(type: BetType, legs: { eventId: string; market?: string; selection?: string; odds?: string; point?: string }[], stake = 100n) { return prisma.bet.create({ data: { userId, type, stake, totalOdds: legs.reduce((x, leg) => x.mul(leg.odds ?? '2'), new Prisma.Decimal(1)), potentialPayout: 1000, idempotencyKey: crypto.randomUUID(), legs: { create: legs.map(leg => ({ provider: 'fixture', providerEventId: leg.eventId, sportKey: 'soccer', homeTeam: 'Home', awayTeam: 'Away', eventStartTime: new Date('2020-01-01'), marketKey: leg.market ?? 'h2h', marketName: leg.market ?? 'h2h', selectionKey: leg.selection ?? 'home', selectionName: leg.selection ?? 'Home', acceptedOdds: leg.odds ?? '2', marketPoint: leg.point })) } }, include: { legs: true } }); }
  it('settles an H2H single win and pays exactly once under concurrent ingestion', async () => { const bet = await createBet('SINGLE', [{ eventId: 'win' }]); await Promise.all([settlement.ingest(final('win', 3, 1)), settlement.ingest(final('win', 3, 1))]); const stored = await prisma.bet.findUniqueOrThrow({ where: { id: bet.id }, include: { legs: true } }); expect(stored.status).toBe('WON'); expect(stored.legs[0].status).toBe('WON'); expect(stored.actualPayout).toBe(200n); expect((await prisma.wallet.findUniqueOrThrow({ where: { id: walletId } })).balance).toBe(1100n); expect(await prisma.ledgerEntry.count({ where: { relatedBetId: bet.id, type: 'SPORTS_WIN' } })).toBe(1); });
  it('settles a losing single without a positive ledger effect', async () => { const bet = await createBet('SINGLE', [{ eventId: 'loss', selection: 'Away' }]); await settlement.ingest(final('loss', 3, 1)); expect((await prisma.bet.findUniqueOrThrow({ where: { id: bet.id } })).status).toBe('LOST'); expect(await prisma.ledgerEntry.count()).toBe(0); expect((await prisma.wallet.findUniqueOrThrow({ where: { id: walletId } })).balance).toBe(900n); });
  it('voids a cancelled single and refunds its stake once', async () => { const bet = await createBet('SINGLE', [{ eventId: 'cancel' }], 500n); const cancelled: NormalizedEventResult = { provider: 'fixture', providerEventId: 'cancel', status: 'CANCELLED' }; await settlement.ingest(cancelled); await settlement.ingest(cancelled); expect((await prisma.bet.findUniqueOrThrow({ where: { id: bet.id } })).status).toBe('VOID'); expect((await prisma.wallet.findUniqueOrThrow({ where: { id: walletId } })).balance).toBe(1400n); expect(await prisma.ledgerEntry.count({ where: { type: 'BET_VOID_REFUND' } })).toBe(1); });
  it('recalculates a winning accumulator with a void leg at odds 1.00', async () => { const bet = await createBet('ACCUMULATOR', [{ eventId: 'a', odds: '2' }, { eventId: 'b', odds: '1.5' }, { eventId: 'c', odds: '2' }], 1000n); await settlement.ingest(final('a', 1, 0)); await settlement.ingest({ provider: 'fixture', providerEventId: 'b', status: 'CANCELLED' }); expect((await prisma.bet.findUniqueOrThrow({ where: { id: bet.id } })).status).toBe('OPEN'); await settlement.ingest(final('c', 2, 0)); const stored = await prisma.bet.findUniqueOrThrow({ where: { id: bet.id } }); expect(stored.status).toBe('WON'); expect(stored.finalOdds?.toString()).toBe('4'); expect(stored.actualPayout).toBe(4000n); });
  it('voids an all-void accumulator and refunds one stake', async () => { const bet = await createBet('ACCUMULATOR', [{ eventId: 'a' }, { eventId: 'b' }]); await settlement.ingest({ provider: 'fixture', providerEventId: 'a', status: 'CANCELLED' }); await settlement.ingest({ provider: 'fixture', providerEventId: 'b', status: 'CANCELLED' }); expect((await prisma.bet.findUniqueOrThrow({ where: { id: bet.id } })).status).toBe('VOID'); expect(await prisma.ledgerEntry.count({ where: { relatedBetId: bet.id, type: 'BET_VOID_REFUND' } })).toBe(1); });
  it('loses an accumulator as soon as any leg loses and never pays', async () => { const bet = await createBet('ACCUMULATOR', [{ eventId: 'a' }, { eventId: 'b', selection: 'Away' }, { eventId: 'c' }]); await settlement.ingest(final('a', 2, 0)); await settlement.ingest(final('b', 2, 0)); expect((await prisma.bet.findUniqueOrThrow({ where: { id: bet.id } })).status).toBe('LOST'); expect(await prisma.ledgerEntry.count()).toBe(0); });
  it('keeps partial/live results open and provider failure makes no mutation', async () => { const bet = await createBet('SINGLE', [{ eventId: 'live' }]); await settlement.ingest({ provider: 'fixture', providerEventId: 'live', status: 'UNKNOWN', homeScore: 2, awayScore: 1 }); provider.getEventResult.mockRejectedValue(new Error('provider down')); await settlement.runOnce(); const stored = await prisma.bet.findUniqueOrThrow({ where: { id: bet.id }, include: { legs: true } }); expect(stored.status).toBe('OPEN'); expect(stored.legs[0].status).toBe('OPEN'); });
  it('detects conflicting final results without reversal or second payout', async () => { const bet = await createBet('SINGLE', [{ eventId: 'conflict' }]); await settlement.ingest(final('conflict', 2, 1)); await settlement.ingest(final('conflict', 1, 2)); expect((await prisma.bet.findUniqueOrThrow({ where: { id: bet.id } })).status).toBe('WON'); expect(await prisma.ledgerEntry.count({ where: { relatedBetId: bet.id } })).toBe(1); expect(await prisma.auditLog.count({ where: { action: 'SPORTS_RESULT_CONFLICT' } })).toBe(1); });
  it('groups worker retrieval to one call per unique event', async () => { await createBet('SINGLE', [{ eventId: 'shared' }]); await createBet('SINGLE', [{ eventId: 'shared' }]); provider.getEventResult.mockResolvedValue(null); await settlement.runOnce(); expect(provider.getEventResult).toHaveBeenCalledTimes(1); });
});