import { SportsError } from '../src/sports/provider.errors';
import { TheOddsApiProvider } from '../src/sports/the-odds-api.provider';
const event = { id: 'event-1', sport_key: 'soccer_epl', sport_title: 'Premier League', commence_time: '2099-01-01T12:00:00.000Z', home_team: 'Home', away_team: 'Away', bookmakers: [{ key: 'book-a', title: 'Book A', markets: [{ key: 'h2h', outcomes: [{ name: 'Home', price: 2.1 }, { name: 'Draw', price: 3.4 }, { name: 'Away', price: 3.1 }] }, { key: 'spreads', outcomes: [{ name: 'Home', price: 1.9, point: -1.5 }] }, { key: 'totals', outcomes: [{ name: 'Over', price: 1.8, point: 2.5 }] }] }] };
describe('TheOddsApiProvider', () => {
  beforeEach(() => { process.env.THE_ODDS_API_KEY = 'test-key-never-logged'; global.fetch = jest.fn(); });
  afterEach(() => { delete process.env.THE_ODDS_API_KEY; jest.restoreAllMocks(); });
  it('normalizes valid sports', async () => { (fetch as jest.Mock).mockResolvedValue(new Response(JSON.stringify([{ key: 'soccer_epl', title: 'Football', active: true }]), { status: 200 })); expect(await new TheOddsApiProvider().getSports()).toEqual([{ key: 'soccer_epl', name: 'Football', active: true }]); });
  it('retains draw and normalizes h2h, spreads and totals as decimal strings', async () => { (fetch as jest.Mock).mockResolvedValue(new Response(JSON.stringify(event), { status: 200 })); const odds = await new TheOddsApiProvider().getEventOdds('soccer_epl', 'event-1'); expect(odds.markets.map(x => x.key)).toEqual(['h2h', 'spreads', 'totals']); expect(odds.markets[0].selections.find(x => x.name === 'Draw')?.price).toBe('3.4'); expect(odds.markets[1].selections[0].point).toBe('-1.5'); });
  it('rejects malformed odds', async () => { (fetch as jest.Mock).mockResolvedValue(new Response(JSON.stringify({ ...event, id: '' }), { status: 200 })); await expect(new TheOddsApiProvider().getEventOdds('soccer_epl', 'event-1')).rejects.toMatchObject({ code: 'SPORTS_PROVIDER_INVALID_RESPONSE' }); });
  it.each([[429, 'SPORTS_PROVIDER_RATE_LIMITED'], [500, 'SPORTS_PROVIDER_UNAVAILABLE']])('maps provider %s safely', async (status, code) => { (fetch as jest.Mock).mockResolvedValue(new Response('secret provider error', { status: status as number })); await expect(new TheOddsApiProvider().getSports()).rejects.toMatchObject({ code }); });
  it('maps timeout/network failure', async () => { (fetch as jest.Mock).mockRejectedValue(new DOMException('aborted', 'AbortError')); await expect(new TheOddsApiProvider().getSports()).rejects.toMatchObject({ code: 'SPORTS_PROVIDER_UNAVAILABLE' }); });
  it('reports an unconfigured provider honestly', async () => { delete process.env.THE_ODDS_API_KEY; await expect(new TheOddsApiProvider().getSports()).rejects.toMatchObject({ code: 'SPORTS_PROVIDER_NOT_CONFIGURED' }); });
});
