export interface FeatureGuide {
  /** Short, catalogue-friendly explanation of the mechanic. */
  description: string;
  /** Detailed explanation of the order of play used by the reference engine. */
  howItWorks: string;
  /** Player-facing rules and constraints that define the mechanic. */
  rules: readonly string[];
}

type GuideDefinition = readonly [description: string, howItWorks: string, ...rules: string[]];

const definitions = {
  "expanding-wilds": [
    "A landed Wild expands to cover its entire reel before wins are evaluated.",
    "After the grid is generated, every reel containing a Wild is filled with Wild symbols. The transformed grid is then passed to the normal win evaluator.",
    "Expansion happens before win evaluation.",
    "Every visible cell on an affected reel becomes Wild.",
    "Expanded Wilds use the game's normal substitution and paytable rules.",
  ],
  "sticky-wilds": [
    "Landed Wilds remain fixed in the same cells for a configured number of later rounds.",
    "The engine records each Wild position after a round. On later rounds it restores those Wilds before evaluation, reduces their remaining duration, and also records any newly landed Wilds.",
    "A sticky Wild is held for the configured number of subsequent rounds; the reference default is three.",
    "A held position stays Wild even when the newly generated symbol underneath it is different.",
    "Removing or resetting the saved feature state releases all held Wilds.",
  ],
  "walking-wilds": [
    "A landed Wild moves one reel to the right on each later round until it leaves the grid.",
    "Wild positions are saved after a round. Before the next grid is evaluated, each saved Wild advances one reel while keeping its row, then its new position is saved again.",
    "Each walker moves exactly one reel per subsequent round.",
    "A walker that moves beyond the final reel expires.",
    "New Wilds can create additional walkers alongside existing ones.",
  ],
  "stacked-wilds": [
    "A Wild extends downward into a vertical stack, creating several adjacent Wild cells on its reel.",
    "Before win evaluation, the engine finds the first Wild on each reel and converts the cells below it to Wild until the configured stack height or the bottom of the reel is reached.",
    "The configured height includes the original Wild; the demo uses a height of three.",
    "Stacks are clipped at the bottom of the visible reel.",
    "The resulting Wild cells participate in normal win evaluation.",
  ],
  "random-wilds": [
    "The game adds a configured number of Wilds to randomly selected cells before evaluation.",
    "For every awarded random Wild, the authoritative RNG selects a visible cell and the engine changes that cell to the game's Wild symbol before checking wins.",
    "The reference default adds one Wild per activation.",
    "The same cell may be selected more than once, so the visible number added can be lower than the number of draws.",
    "Feature upgrades can increase the configured Wild count.",
  ],
  "spreading-wilds": [
    "Every Wild spreads into its horizontally and vertically adjacent cells before wins are checked.",
    "The engine first records all valid orthogonal neighbours of the Wilds on the generated grid, then changes those cells to Wild in one simultaneous transformation pass.",
    "Only cells directly above, below, left, or right of an original Wild are affected.",
    "Diagonal cells are not included.",
    "Newly created Wilds do not spread again during the same pass.",
  ],
  "multiplier-wilds": [
    "A win that uses a Wild is multiplied by a configured factor.",
    "The grid is evaluated first. If at least one winning combination contains a Wild, the engine multiplies the payouts of Wild-containing wins and recalculates the round total.",
    "Only wins whose winning cells include a Wild are multiplied.",
    "The reference default multiplier is 2x.",
    "The multiplier changes the award, not the symbols or the original bet.",
  ],
  "shifting-wilds": [
    "A landed Wild shifts one reel to the left on each later round until it exits the grid.",
    "The engine saves Wild positions after a round and restores each one a reel further left before the next grid is evaluated. Valid shifted positions remain in feature state.",
    "Each saved Wild moves exactly one reel per subsequent round.",
    "A Wild expires when its next position would be left of the first reel.",
    "Newly landed Wilds can join the shifting sequence.",
  ],
  "mystery-wilds": [
    "A random number of randomly placed cells turn into Wilds before evaluation.",
    "The engine first draws how many Mystery Wilds will be applied, then independently draws a target cell for each transformation and converts it to Wild.",
    "At least one placement is attempted when the feature is active.",
    "The maximum number of placements is configurable; the demo caps it at two.",
    "Repeated selection of the same cell is allowed.",
  ],
  "colossal-wilds": [
    "A Wild activation creates one large 2x2 Wild block on the grid.",
    "When at least one Wild is present, the engine selects an origin cell and fills the origin plus the available cells one row and reel across with Wilds before evaluation.",
    "The feature activates only when the generated grid already contains a Wild.",
    "The block is clipped at the right and bottom grid edges.",
    "The large symbol is evaluated as four ordinary Wild cells.",
  ],
  "wild-reels": [
    "One randomly selected reel becomes entirely Wild before the spin is evaluated.",
    "The authoritative RNG chooses a reel, every visible cell on it is replaced with the Wild symbol, and the transformed grid is evaluated normally.",
    "Exactly one reel is selected per activation.",
    "All visible rows on that reel become Wild.",
    "No extra award is added unless the transformed grid forms a payable win.",
  ],
  "wild-respin": [
    "Any landed Wilds lock in place while the rest of the grid respins once.",
    "After the base spin, the engine records every Wild cell, generates a fresh full grid, restores the recorded Wilds, evaluates the respun grid, and adds its wins to the round.",
    "At least one Wild on the base grid is required.",
    "All base-grid Wild positions are retained for the respin.",
    "The base-spin award and respin award are both included in the round total.",
  ],

  "free-spins": [
    "A qualifying trigger awards a configured series of additional spins at the same bet basis.",
    "Once the trigger resolves, the engine runs the configured number of free-spin grids, evaluates each one, adds their awards to the triggering round, and emits a start, per-spin, and end record.",
    "The reference default is eight free spins unless the game config overrides it.",
    "Free-spin awards use the triggering bet as their payout basis and do not add another stake.",
    "A safety limit ends the sequence after 50 played spins, including additions.",
  ],
  "retriggering-free-spins": [
    "Landing enough Scatters during free spins adds more spins to the remaining total.",
    "After each free spin is evaluated, its trigger grid is counted. If it meets the configured Scatter threshold, the engine adds the configured retrigger quantity to the spins still to play.",
    "The reference threshold is three Scatters and the default award is three extra spins.",
    "Retriggers are checked only inside an active free-spins sequence.",
    "Added spins remain subject to the overall 50-spin safety limit.",
  ],
  "increasing-multipliers": [
    "The win multiplier rises on every successive free spin.",
    "The first free spin uses 1x, the second 2x, the third 3x, and so on. The engine multiplies that spin's evaluated wins before adding them to the free-spins total.",
    "The multiplier is based on the zero-based free-spin position plus one.",
    "A losing spin still advances the multiplier for the next spin.",
    "The multiplier resets when a new free-spins sequence starts.",
  ],
  "persistent-multipliers": [
    "A free-spins multiplier is saved and grows between separate bonus sequences.",
    "A sequence begins with the multiplier stored in authoritative feature state. When the sequence ends, the number of spins played is added to that stored multiplier for use on a later trigger.",
    "The stored multiplier starts at 1x when no prior value exists.",
    "Every win in a sequence uses the same multiplier available at that sequence's start.",
    "Resetting feature state returns the persistent multiplier to its initial value.",
  ],
  "sticky-symbols": [
    "A configured symbol remains fixed in its cells for a set number of later rounds.",
    "The engine saves positions occupied by the target symbol. On subsequent grids it restores the target into those cells before evaluation and counts down each cell's remaining duration.",
    "The target symbol and duration are configured by the game; the demo holds Wilds for two later rounds.",
    "New target symbols can become sticky while earlier ones are still active.",
    "The saved positions are part of authoritative feature state.",
  ],
  "expanding-reels": [
    "The visible reels gain extra rows as a free-spins sequence progresses.",
    "The first free spin uses the base layout. Each later spin adds one row to every reel until the configured maximum extra-row count is reached, then the larger grid is generated and evaluated.",
    "Growth is tied to the free-spin index, not to whether the prior spin won.",
    "Every reel gains the same number of rows in the reference implementation.",
    "The layout returns to its configured base size after the sequence.",
  ],
  "enhanced-symbols": [
    "A chosen symbol pays at an enhanced multiplier during free spins.",
    "The grid is evaluated normally, then any win containing the configured enhanced symbol has its payout multiplied before the free-spin result is added to the sequence total.",
    "The enhancement applies only during the free-spin phase.",
    "Only wins containing the configured symbol receive the multiplier.",
    "The demo enhances the high-value Explorer symbol at 2x.",
  ],
  "choose-your-bonus": [
    "The player chooses between free-spin packages with different spin counts and starting multipliers.",
    "On a qualifying trigger, the server computes every configured package using authoritative draws, then presents the package labels. Choosing one reveals and settles the already-computed result for that package.",
    "Each package defines both a spin count and a starting multiplier.",
    "Only the selected package award is applied.",
    "The choice changes which precomputed package is accepted; it does not move award generation to the client.",
  ],
  "free-spins-trail": [
    "Scatters collected during free spins advance a trail that awards extra spins at milestones.",
    "Each free spin adds its landed Scatter count to a stored trail meter. Every time the meter reaches the configured step, the step amount is consumed and one spin is added to the remaining sequence.",
    "All landed Scatters count, even when they do not meet a normal retrigger threshold.",
    "Multiple milestones can be crossed on one spin.",
    "Unspent trail progress remains in authoritative feature state until reset.",
  ],

  "respins": [
    "A losing base spin receives one or more fresh full-grid attempts.",
    "If the base grid has no win, the engine generates and evaluates a new full grid. It repeats up to the configured count and stops early as soon as a respin wins.",
    "Respins are offered only after a zero-win base result.",
    "The reference default allows one respin.",
    "Any respin win is added to the same authoritative round result.",
  ],
  "hold-and-win": [
    "Trigger coins lock while empty cells respin with three chances to land more coins.",
    "When enough configured trigger symbols land, those cells lock. Bonus or Collect symbols are the default, while a game may route a Scatter trigger into the module and select a dedicated themed coin symbol for the locked cells. Empty cells are tested on each respin; any new coin locks and restores the life counter to three, while a blank respin consumes one life.",
    "The reference trigger is three qualifying symbols and the sequence starts with three lives.",
    "The feature ends when the grid is full, three consecutive blank respins occur, or the 50-respin safety limit is reached.",
    "The final award is locked-coin count multiplied by bet and the configured coin multiplier.",
  ],
  "lock-and-respin": [
    "Qualifying symbols lock in place while the remaining cells respin until the chances run out.",
    "The reference engine uses the same three-life loop as Hold and Win: new Bonus or Collect symbols lock and reset lives to three; a respin with no new symbol removes one life.",
    "At least the configured trigger count must land on the base grid.",
    "The sequence ends on a full grid, after three blank respins, or at the 50-respin safety limit.",
    "Every locked symbol contributes the configured coin value to the final award.",
  ],
  "reel-respin": [
    "After a losing base spin, one randomly selected reel is regenerated while the others stay put.",
    "The engine chooses one reel, draws a replacement symbol for each of its cells, evaluates the updated grid, and records any resulting wins as part of the original round.",
    "The feature runs only when the base spin and any earlier respin rule have not produced an award.",
    "Exactly one reel is redrawn.",
    "All non-selected reels keep their base-grid symbols.",
  ],
  "nudge": [
    "One reel shifts down by a single cell after a losing spin, revealing one new symbol.",
    "The engine selects a reel, inserts a freshly drawn symbol at its top, moves the existing symbols down one row, drops the bottom symbol, and evaluates the adjusted grid.",
    "The nudge is attempted only when no earlier award has resolved the losing base spin.",
    "Exactly one randomly selected reel moves one position.",
    "Only wins on the nudged grid are added by this feature.",
  ],
  "rewind": [
    "A losing round can restore the previous round's final base grid and pay it again.",
    "The engine remembers the last base grid. If a later base spin loses, it restores that grid, validates that it still matches the layout, reevaluates it, and applies the configured rewind multiplier.",
    "A compatible saved grid from an earlier round is required.",
    "The reference default multiplier is 1x; the demo uses 2x.",
    "The current base grid is saved after the round for a possible later rewind.",
  ],
  "second-chance": [
    "A losing spin has a configured probability of receiving one extra full-grid attempt.",
    "After a zero-win base outcome, the server draws against the feature's basis-point chance. On success it generates and evaluates one replacement grid.",
    "The probability is configured from 0 to 10,000 basis points.",
    "The demo sets the chance to 10,000 basis points so the extra attempt is always visible.",
    "The extra result remains part of the same round and uses the same bet basis.",
  ],

  "mystery-symbols": [
    "All instances of a designated Mystery symbol reveal as one configured target symbol.",
    "Before evaluation, the engine scans the generated grid and replaces every source-symbol cell with the target symbol, emitting each reveal as a symbol transformation.",
    "Only the configured source symbol is changed.",
    "Every matching source reveals as the same target during that activation.",
    "Wins are evaluated after the reveal.",
  ],
  "symbol-upgrade": [
    "A designated lower-value symbol is converted into a higher-value symbol before evaluation.",
    "The engine replaces every occurrence of the configured source symbol with the configured target, then evaluates the upgraded grid against the ordinary paytable.",
    "All matching source cells are upgraded in one pass.",
    "The configured target determines the new symbol's payout behavior.",
    "No direct award is added if the upgrades do not form a win.",
  ],
  "symbol-swap": [
    "Every occurrence of one configured symbol is replaced by another before wins are checked.",
    "The engine scans all visible cells, transforms the configured source into the configured target, and then evaluates the resulting grid.",
    "The change is one-way; target symbols do not turn back into the source.",
    "Only exact source-symbol matches are affected.",
    "The transformed symbols use the target's normal paytable role.",
  ],
  "symbol-removal": [
    "A chosen low-value symbol is removed and replaced with newly drawn symbols before evaluation.",
    "For each source-symbol cell, the engine makes an authoritative weighted draw from the remaining symbol pool and inserts the replacement before checking wins.",
    "The removed symbol is excluded from its own replacement pool.",
    "Every matching source cell is processed independently.",
    "Replacement weights come from the game's configured symbol weights.",
  ],
  "symbol-clone": [
    "One symbol is copied into a configured number of randomly selected cells.",
    "The engine uses the configured source, or the top-left grid symbol when none is configured, then draws target cells and overwrites them with that symbol before evaluation.",
    "The reference default attempts two clone placements.",
    "The same destination can be drawn more than once.",
    "Cloning changes the evaluated grid but does not itself guarantee a win.",
  ],
  "symbol-expansion": [
    "A designated symbol expands to fill every reel on which it appears.",
    "Before evaluation, each reel containing the configured symbol is replaced entirely with that same symbol and recorded as a reel transformation.",
    "Only reels already containing the target symbol expand.",
    "All visible cells on an affected reel become the target symbol.",
    "The expanded grid is evaluated normally.",
  ],
  "split-symbols": [
    "A configured symbol counts as a multiplied contribution whenever it appears in a win.",
    "After normal evaluation, the engine finds wins containing the split symbol and multiplies only those win payouts by the configured factor.",
    "The reference minimum and default factor is 2x.",
    "Wins that do not include the split symbol are unchanged.",
    "The symbol remains one visible cell; the split is represented in award calculation.",
  ],
  "oversized-symbols": [
    "One randomly selected normal symbol appears as a large square block spanning several cells.",
    "The server chooses a normal symbol and origin, adjusts the origin to keep the configured square on the grid, fills that area with copies of the symbol, and then evaluates the grid.",
    "The configured size is at least 2x2; the demo uses 2x2.",
    "The block is kept within the visible grid where its dimensions allow.",
    "Each covered cell counts separately for win evaluation.",
  ],

  "cascading-reels": [
    "Winning symbols are removed and replaced repeatedly while each new grid keeps winning.",
    "After every evaluated win, all unique winning cells are removed, symbols above fall into the gaps, new weighted symbols enter, and the new grid is evaluated as the next cascade.",
    "Only cells belonging to wins are removed.",
    "Cascades stop on a no-win grid or at the game's configured maximum.",
    "Awards from every cascade are added to the same round total.",
  ],
  "avalanche-wins": [
    "Each win clears its symbols so replacements can fall in and create another win.",
    "The reference engine resolves Avalanche Wins with the shared cascade loop: winning cells disappear, surviving symbols drop, replacements enter from above, and the grid is reevaluated.",
    "A new avalanche occurs only when the current grid has a win.",
    "Each stage is evaluated and awarded separately.",
    "The chain ends on the first losing replacement grid or the cascade limit.",
  ],
  "increasing-cascade-multiplier": [
    "Wins on later cascades receive a multiplier that rises with the cascade count.",
    "The initial grid pays at 1x. After symbols drop, wins on cascade one are multiplied by 2x, cascade two by 3x, and so on before being added to the round total.",
    "The multiplier applies only after at least one cascade has occurred.",
    "Each winning cascade advances the factor for the next replacement grid.",
    "The multiplier resets for the next paid round.",
  ],
  "cluster-pays": [
    "Matching symbols pay when they form a large enough connected cluster anywhere on the grid.",
    "The cluster evaluator flood-fills matching normal symbols and Wild substitutes through shared horizontal or vertical edges, then uses the connected cell count to select the paytable award.",
    "Diagonal contact alone does not connect a cluster.",
    "A cluster may begin on any reel or row.",
    "The paytable determines the minimum cluster size and award.",
  ],
  "connected-pays": [
    "Matching symbols pay when an unbroken orthogonal connection reaches the configured size.",
    "The reference implementation uses connected-component evaluation: matching symbols and Wilds are joined across shared left, right, top, or bottom edges and each component is checked against the paytable.",
    "Diagonal cells are not connected.",
    "Connections do not have to start on the first reel.",
    "Separate groups of the same symbol are evaluated independently.",
  ],
  "pay-anywhere": [
    "A symbol pays from its total count on the grid, regardless of reel order or adjacency.",
    "The count evaluator totals each eligible non-Scatter, non-Bonus symbol across all visible cells and chooses the best paytable entry at or below that count.",
    "Symbols do not need to touch or start on the first reel.",
    "Each symbol type is counted separately.",
    "Scatter and Bonus symbols use their own scatter-pay rules.",
  ],
  "symbol-drop": [
    "Winning cells disappear and new symbols drop into their places for another evaluation.",
    "The mechanic uses the shared cascade loop: unique winning cells are removed, surviving symbols retain their relative order, replacements enter at the top, and the updated grid is checked again.",
    "Drops continue only while the replacement grid wins.",
    "Every drop uses authoritative weighted symbol draws.",
    "All stage awards accumulate within the current round.",
  ],
  "chain-reactions": [
    "A win removes both its winning cells and their immediate neighbours, creating a wider reaction.",
    "On the first winning grid the feature starts, then the cascade remover expands the cleared set to orthogonally adjacent non-Scatter cells before dropping replacements and reevaluating.",
    "Neighbour expansion includes left, right, above, and below, but not diagonals.",
    "Scatter cells are protected from neighbour-only removal.",
    "The reaction continues under the normal cascade stop and limit rules.",
  ],

  "variable-height-ways": [
    "Reels have different visible heights, so the number of possible symbol paths varies across the grid.",
    "The engine generates the configured row count for each reel and evaluates matching symbols from the first reel across consecutive reels. Matching positions on each reel multiply the number of ways.",
    "The demo uses reel heights of 2, 3, 4, 3, and 2.",
    "A way must match on consecutive reels beginning with the first reel.",
    "The award is the paytable value multiplied by the number of matching ways.",
  ],
  "ways-to-win": [
    "Matching symbols pay on adjacent reels without requiring fixed paylines.",
    "For each symbol on the first reel, the evaluator counts matching symbols or Wilds on consecutive reels. The counts per reel are multiplied to produce the number of payable ways.",
    "A payable way starts on the first reel and cannot skip a reel.",
    "Row position does not have to match between reels.",
    "The paytable award is multiplied by the calculated number of ways.",
  ],
  "expanding-grid": [
    "Winning rounds permanently add rows to later rounds until the grid reaches its configured limit.",
    "After a winning round, the engine increments a saved expansion meter. Before the next round it adds that many rows to every reel, up to the configured maximum, and evaluates the larger generated grid.",
    "Growth is earned by a positive round award and applies from the following round.",
    "Every reel grows by the same number of rows.",
    "Resetting feature state restores the base layout.",
  ],
  "extra-reel": [
    "A probability check can add one extra reel to the current round.",
    "Before grid generation, the server draws against the configured basis-point chance. On success it increases the reel count by one and gives the new reel the last configured reel height.",
    "At most one reel is added per round.",
    "The demo sets the chance to 10,000 basis points so the resize is always shown.",
    "The extra reel applies only to the current derived round layout.",
  ],
  "reel-growth": [
    "A winning round makes one random reel taller on later rounds.",
    "After a positive award, the engine selects a reel and increments its saved growth meter. At the start of later rounds, each reel gains the rows stored for it.",
    "Only one reel receives a growth increment after each winning round.",
    "Each reel can gain at most two extra rows in the reference implementation.",
    "Saved reel heights return to normal when feature state is reset.",
  ],
  "reel-split": [
    "One reel is copied into the reel immediately to its right before evaluation.",
    "The engine chooses a source from all reels except the last, then replaces the next reel's cells with the source reel's symbols, repeating rows if the heights differ.",
    "The copied reel is always directly to the source's right.",
    "The target reel is overwritten for the current evaluation.",
    "The transformation does not add an award unless the copied layout forms a win.",
  ],
  "random-reel-modifier": [
    "A random reel receives one of three modifiers: Wild, synchronised, or stacked.",
    "The server draws a modifier and a target reel. It either fills the reel with Wilds, copies a neighbouring reel, or fills it with one randomly selected normal symbol before evaluating the grid.",
    "One modifier and one reel are selected per activation.",
    "The available modifiers are wild reel, synchronised reel, and stacked symbol.",
    "All modifier choices and symbol draws are authoritative RNG evidence.",
  ],
  "adjacent-pays": [
    "Matching symbols pay across consecutive adjacent reels without fixed line shapes.",
    "The reference demo uses ways evaluation: matches can occupy any row, but they must continue reel by reel from the leftmost reel. Matching counts on each reel determine the number of ways.",
    "A win begins on the first reel and cannot skip an intervening reel.",
    "Vertical alignment is not required.",
    "The paytable threshold and calculated ways determine the award.",
  ],

  "symbol-collection": [
    "Every landed target symbol is added to a collection total that persists across rounds.",
    "After each grid is evaluated, the engine counts the configured Collect symbol, adds that count to authoritative feature state, and emits the new total for presentation.",
    "Only the configured target symbol advances the collection.",
    "The total persists between rounds until feature state is reset.",
    "Collection progress does not itself pay unless combined with another configured collection reward.",
  ],
  "meter-progress": [
    "Landed trigger symbols fill a meter that pays whenever it reaches its target.",
    "The engine adds landed Scatters, or Bonus symbols when no Scatters exist, to a persistent meter. At the configured target it awards a bet multiplier and carries any excess progress forward.",
    "The demo target is three symbols and its award is 5x bet.",
    "A single spin can cross the target and leave remainder progress.",
    "The meter and award are calculated in authoritative feature state.",
  ],
  "level-up-bonus": [
    "Collected symbols raise a persistent level and award prizes when a new level is reached.",
    "Bonus symbols accumulate in a meter. The engine divides the total by the configured symbols-per-level value, detects newly crossed levels, starts the level-up feature, and awards for the levels gained.",
    "The demo requires three collected symbols per level.",
    "Progress and the highest awarded level persist across rounds.",
    "Only newly reached levels pay; previously awarded levels are not paid again.",
  ],
  "persistent-collection": [
    "Collect symbols accumulate over multiple rounds and award a prize at a target total.",
    "The engine adds each landed Collect or Bonus symbol to a saved meter. When the target is met, it pays the configured bet multiplier and subtracts the target so extra progress carries forward.",
    "The demo target is six symbols with a 10x-bet award.",
    "Progress survives between rounds.",
    "Resetting the scenario clears the saved collection.",
  ],
  "prize-ladder": [
    "Collected symbols climb a ladder of increasingly valuable prize rungs.",
    "Landed Scatters or Bonus symbols move the saved rung forward. Reaching or passing the last configured rung awards its multiplier and returns the ladder to its starting position.",
    "The demo ladder values are 2x, 4x, and 6x bet.",
    "Progress persists when the top has not yet been reached.",
    "The top-rung award is server-calculated and the meter resets after payment.",
  ],
  "map-journey-bonus": [
    "Landed symbols move a marker around a persistent map whose prize tiles can award wins.",
    "The number of landed Bonus or Scatter symbols advances the saved map position, wrapping at the end. The destination tile is read from the configured map and pays its bet multiplier when non-zero.",
    "Movement equals the qualifying-symbol count on the spin.",
    "The map wraps back to its beginning after the final tile.",
    "Only the destination tile pays; zero-value tiles record movement without an award.",
  ],
  "feature-upgrade": [
    "Collected symbols level up another mechanic for later rounds.",
    "The engine tracks Collect or Bonus symbols, calculates an upgrade level at each configured milestone, and stores that level against a target feature. The reference target is Random Wilds, where each level adds another Wild placement.",
    "The demo gains one level for every three collected symbols.",
    "An upgrade applies only when its calculated level exceeds the saved level.",
    "Upgrade state persists until reset.",
  ],
  "pot-collection": [
    "Bonus coins build a persistent pot, and a Collector symbol cashes out the stored total.",
    "Each Bonus symbol adds one coin to the saved pot. When a Collect symbol, or a Wild fallback, is present, the engine pays stored coins times bet and the configured coin multiplier, then empties the pot.",
    "Coins can accumulate across rounds without paying.",
    "At least one Collector must land to cash out a non-empty pot.",
    "The pot resets to zero immediately after its authoritative award.",
  ],

  "coin-values": [
    "Bonus symbols carry displayed bet-multiplier values that are summed into a direct prize.",
    "The engine assigns configured values to Bonus cells using a stable reel-and-row pattern, totals the visible values, and awards that total multiplied by the bet.",
    "The demo cycles through coin values of 1x, 2x, and 5x.",
    "Every visible Bonus coin contributes to the award.",
    "The values and exact prize are included in the server event evidence.",
  ],
  "cash-collect": [
    "Value-bearing Bonus coins pay only when a Collector symbol lands with them.",
    "Bonus cells receive configured values and are summed, but the engine awards the total only if at least one symbol of the configured collector kind is present on the same grid.",
    "The demo uses Wild as the Collector kind and coin values of 1x, 2x, and 5x.",
    "Without a Collector, the visible coin values do not pay through this feature.",
    "With a Collector, all visible coin values are multiplied by the bet and awarded once.",
  ],
  "tumble-multiplier-orbs": [
    "Special orbs receive weighted multiplier values that add together and multiply tumble wins.",
    "When an orb appears, the server draws its value from the configured weighted table. Values surviving a cascade stay attached to their cells; all visible orb values are summed and multiply the evaluated win for that grid.",
    "Default orb values range from 2x to 500x with higher values weighted more rarely.",
    "The multiplier applies only when the grid has a positive win.",
    "During free spins, orb sums accumulate across the sequence before multiplying each win.",
  ],
  "multiplier-symbols": [
    "Landed Bonus symbols select a win multiplier from a configured value table.",
    "After evaluation, the engine counts visible Bonus symbols and uses that count to choose the corresponding configured multiplier, capped at the last available value, then multiplies the grid's wins.",
    "The reference values are 2x, 3x, and 5x.",
    "At least one Bonus symbol and a positive evaluated win are required.",
    "The chosen multiplier applies to all wins on that evaluated grid.",
  ],
  "additive-multipliers": [
    "Each Bonus symbol adds a configured amount to one combined win multiplier.",
    "The engine counts the Bonus symbols, multiplies that count by the configured value, and uses the result as the factor applied to the evaluated wins.",
    "The reference value is 2 per Bonus symbol, so three symbols produce a 6x factor.",
    "At least one Bonus symbol and a positive win are required.",
    "Contributions are added together before the single multiplier is applied.",
  ],
  "multiplying-multipliers": [
    "Each Bonus symbol compounds the configured multiplier with the others.",
    "The engine raises the configured value to the number of landed Bonus symbols and multiplies the evaluated wins by that compound factor.",
    "The reference value is 2, so three symbols produce 2x × 2x × 2x = 8x.",
    "Compounding is capped at six contributing Bonus symbols.",
    "A positive evaluated win is required for the factor to change an award.",
  ],
  "random-prize": [
    "An independent probability check can add one randomly selected fixed prize to the round.",
    "Before evaluation, the server tests the configured basis-point chance and, on success, draws a multiplier from the configured values. After evaluation it adds that multiplier times the bet as a prize.",
    "The reference chance is 1,500 basis points; the demo forces activation at 10,000.",
    "The reference prize values are 2x, 5x, and 10x bet.",
    "The prize can pay even when the normal grid has no win.",
  ],
  "instant-win": [
    "Landing a configured number of Bonus symbols awards a fixed bet multiplier immediately.",
    "After the grid is evaluated, the engine counts Bonus symbols. Meeting or exceeding the threshold adds the configured instant prize to the round total.",
    "The demo requires three Bonus symbols and awards 10x bet.",
    "Extra symbols above the threshold do not multiply this fixed award again.",
    "Normal grid wins are calculated separately and can pay alongside it.",
  ],
  "prize-boost": [
    "Every compatible direct prize in the round is multiplied by a configured boost.",
    "The reference prize pipeline applies the boost when a Random Prize, Coin Value, Cash Collect, Instant Win, or collection award is added, and emits the boost before the first affected prize.",
    "The reference and demo boost is 2x.",
    "The boost affects direct prize awards, not ordinary evaluated symbol wins.",
    "If no compatible prize is awarded, the boost adds nothing by itself.",
  ],
  "double-or-nothing": [
    "After a win, the player may collect it or risk the full amount for a chance to double it.",
    "The server draws the gamble result before presenting Collect and Double. Collect keeps the existing win; choosing Double either adds the same amount again or removes the existing amount.",
    "The option appears only after a positive round win.",
    "Collect carries no adjustment; Double settles at either 2x or zero total win.",
    "The client choice reveals a server-precomputed outcome and cannot alter its odds.",
  ],
  "gamble-feature": [
    "After a win, the player can risk it by choosing red or black for a double-or-lose result.",
    "The server pre-draws the winning colour, then presents both choices. A match adds an amount equal to the original win; a mismatch subtracts it.",
    "The gamble is available only when the round has a positive win.",
    "A correct choice produces 2x the original win; an incorrect choice produces zero.",
    "The winning colour and settlement remain server-authoritative.",
  ],

  "progressive-jackpot": [
    "Each bet contributes to a persistent pool that can be won on a random trigger.",
    "The engine adds the configured share of the bet to the saved progressive meter, records the contribution, then performs a basis-point trigger draw. A hit pays the pool plus the configured seed and resets the pool.",
    "The reference contribution is 1% of bet and trigger chance is 5 in 10,000; the demo forces the trigger.",
    "At least one minor unit is contributed each enabled round.",
    "The award and reset are calculated from authoritative persistent state.",
  ],
  "fixed-jackpot": [
    "Landing enough Jackpot symbols awards a fixed multiple of the bet.",
    "The engine counts Jackpot-kind symbols on the trigger grid and, at the configured threshold, adds the configured multiplier as a jackpot award.",
    "The demo requires three Jackpot symbols.",
    "The demo fixed award is 100x bet.",
    "The prize does not depend on a growing pool.",
  ],
  "local-jackpot": [
    "A locally tracked contribution pool grows with play and pays on a random trigger.",
    "The engine contributes a configured portion of each bet to local feature state, draws against the local trigger chance, and on a hit pays the stored pool plus its configured seed before resetting it.",
    "The reference contribution is 1.5% of bet with a 20-in-10,000 trigger; the demo forces a hit.",
    "At least one minor unit is contributed on every enabled round.",
    "The pool belongs to the reference game's saved state rather than a network-wide service.",
  ],
  "mystery-jackpot": [
    "An independent random trigger awards one value from a configured jackpot prize table.",
    "The server first tests the basis-point trigger chance and, on success, draws one of the configured multipliers and adds it as a Mystery jackpot award.",
    "The reference trigger chance is 30 in 10,000; the demo forces activation.",
    "The demo prize values are 20x, 50x, and 100x bet.",
    "No Jackpot symbol or contribution pool is required.",
  ],
  "jackpot-wheel": [
    "Landing enough Jackpot symbols opens a wheel that reveals a weighted jackpot tier.",
    "The server draws Mini, Minor, Major, or Grand and its exact award before showing the wheel. Pressing Spin resolves that continuation and publishes the selected tier's award.",
    "The demo requires three Jackpot symbols to open the wheel.",
    "Default tier weights are 60, 25, 10, and 5 respectively.",
    "The wheel animation presents the precomputed result; it does not generate the award.",
  ],
  "jackpot-tiers": [
    "The number of landed Jackpot symbols selects a fixed Mini, Minor, Major, or Grand tier.",
    "The engine counts Jackpot symbols: three select Mini, four Minor, five Major, and six or more Grand, then awards that tier's configured bet multiplier.",
    "Fewer than three Jackpot symbols do not trigger a tier.",
    "The reference defaults are 10x, 25x, 100x, and 500x bet.",
    "Only one highest matching tier pays per round.",
  ],
  "jackpot-pick-bonus": [
    "A Jackpot-symbol trigger presents several picks, each hiding a precomputed jackpot tier.",
    "The server draws a weighted tier and award for every pick before presenting the choices. Selecting one settles only that choice and emits its Jackpot award.",
    "The demo requires three Jackpot symbols and presents three choices.",
    "Each hidden tier uses the configured Mini-to-Grand weights and values.",
    "The client cannot redraw or change the award behind a choice.",
  ],
  "must-win-by-jackpot": [
    "A contribution pool is forced to pay no later than a configured monetary ceiling.",
    "Each round adds a configured share of bet to persistent state. When the pool reaches the bet-based must-win-by ceiling, the engine awards the full pool and resets it.",
    "The reference contribution is 2% of bet and the default ceiling is 20x bet.",
    "The demo contributes 100% with a 1x-bet ceiling so the forced award is visible immediately.",
    "The ceiling check and forced settlement are server-authoritative.",
  ],

  "pick-and-click-bonus": [
    "A trigger presents several concealed picks, and the selected pick reveals a prize.",
    "The server assigns an award from the configured prize multipliers to every choice before presenting them. Clicking one resolves the pending action and applies only that precomputed award.",
    "The demo presents three choices with prizes drawn from 1x, 2x, and 4x bet.",
    "Exactly one choice is settled.",
    "Choice presentation never changes the underlying authoritative result.",
  ],
  "wheel-bonus": [
    "A trigger opens a wheel-style choice that resolves to a configured prize.",
    "The reference engine precomputes the award choices on the server and marks the action as a wheel presentation. The player's interaction resolves the selected server-held award.",
    "The demo uses three selectable outcomes drawn from 1x, 2x, and 4x bet.",
    "Only one outcome is applied.",
    "Wheel timing and animation do not influence the result.",
  ],
  "board-game-bonus": [
    "A trigger presents a board-themed set of moves that lead to prize outcomes.",
    "In the reference implementation, the board is a presentation over authoritative choices: the server assigns a prize to each move before the action appears and settles the selected move.",
    "The demo offers three moves with awards drawn from 1x, 2x, and 4x bet.",
    "One move resolves the bonus.",
    "Board position or animation cannot alter the precomputed award.",
  ],
  "treasure-chest-bonus": [
    "A trigger presents treasure chests, with the selected chest revealing a prize.",
    "Before the chests appear, the server draws an award for every choice from the configured multipliers. Opening a chest resolves and applies only its stored award.",
    "The demo displays three choices using 1x, 2x, and 4x-bet prizes.",
    "Only one chest can be settled.",
    "The reveal is presentation; all prize draws are already recorded by the server.",
  ],
  "match-three-bonus": [
    "A trigger starts a match-themed selection that resolves to a prize outcome.",
    "The reference demo represents the mechanic with authoritative concealed choices. Each choice receives a server-drawn multiplier, and the selected choice is the only award applied.",
    "The demo offers three choices with values drawn from 1x, 2x, and 4x bet.",
    "One selection completes the reference bonus.",
    "The matching presentation does not generate or modify prize values on the client.",
  ],
  "skill-style-bonus": [
    "A skill-themed interaction presents player actions while keeping the award independent of reaction skill.",
    "The server precomputes a prize for each available action before the sequence is shown. The chosen action reveals its stored value; aiming, timing, or animation on the client cannot change it.",
    "The demo provides three actions with prizes drawn from 1x, 2x, and 4x bet.",
    "One action settles the bonus.",
    "The interaction is skill-style presentation, not a client-authoritative game of skill.",
  ],
  "choose-a-path-bonus": [
    "A trigger lets the player select a path, with each route hiding a prize outcome.",
    "The server assigns a prize to every route before displaying the path choice. Selecting a route resolves its stored award and completes the action.",
    "The demo presents three paths using prize multipliers of 1x, 2x, and 4x bet.",
    "Only the selected route pays.",
    "The visual route does not recalculate the server-precomputed result.",
  ],
  "boss-battle-bonus": [
    "A trigger presents battle-themed actions that reveal prize outcomes.",
    "The reference engine models battle actions as authoritative choices: awards are drawn and stored on the server first, then the selected action resolves its assigned value.",
    "The demo offers three actions with prizes drawn from 1x, 2x, and 4x bet.",
    "One action completes the reference battle.",
    "Client timing, animation, or apparent damage cannot change the award.",
  ],

  "scatter-trigger": [
    "Landing the required number of Scatter symbols starts the game's configured bonus feature.",
    "The engine counts Scatter-kind symbols on the configured trigger grid. Meeting or exceeding the threshold marks the round as triggered so Free Spins or an interactive bonus can start.",
    "The reference threshold is three Scatters unless configured otherwise.",
    "The trigger can count the initial transformed grid or the final grid, according to configuration.",
    "Scatter paytable wins are separate from the feature trigger.",
  ],
  "bonus-buy": [
    "A feature purchase charges a configured stake multiple and guarantees the bonus trigger.",
    "When the round requests Bonus Buy, the engine reserves the configured purchase cost and forces enough Scatters onto the generated grid to meet the Scatter trigger before starting the bonus.",
    "The reference purchase cost is 100x bet.",
    "Bonus Buy cannot be combined with an ante bet in the same request.",
    "The demo forces the purchase path so its trigger sequence is always visible.",
  ],
  "random-feature": [
    "A probability check can apply a random Wild burst, symbol upgrade, or win multiplier.",
    "The server tests the configured activation chance, then draws one of three modifiers. It either adds two Wilds, upgrades low symbols, or stores a multiplier that applies to a positive evaluated win.",
    "The reference activation chance is 2,000 basis points; the demo forces activation.",
    "Exactly one modifier is chosen on a successful activation.",
    "All chance, modifier, and cell draws are authoritative RNG evidence.",
  ],
  "feature-drop": [
    "Bonus symbols count down a persistent meter, and reaching zero triggers the linked bonus.",
    "Each landed Bonus symbol reduces the saved remaining count. When the count reaches zero, the engine starts the feature and resets the meter to its configured target.",
    "The demo target is three Bonus symbols.",
    "Progress carries between rounds until the target is completed.",
    "A completion can trigger the configured Free Spins sequence in the same round.",
  ],
  "feature-combination": [
    "When enough different mechanics contribute to a winning round, their combined result receives a multiplier.",
    "After all feature awards are resolved, the engine counts distinct contributing feature IDs. If the configured minimum is met and the round has a win, it multiplies the complete current total.",
    "The demo requires two contributing mechanics and applies a 2x multiplier.",
    "The combination feature does not count itself as a contributor.",
    "No multiplier is applied on a zero-win round.",
  ],
  "near-miss-enhancement": [
    "A one-short Scatter result receives a distinct near-miss presentation without changing the award.",
    "If the bonus did not trigger and the grid contains exactly one fewer Scatter than required, the engine emits a near-miss event for the client to present.",
    "The condition must be exactly trigger threshold minus one.",
    "A true trigger never also receives a near-miss event.",
    "Near-miss presentation does not add symbols, respins, or prize value.",
  ],
  "ante-bet": [
    "An optional higher stake increases Scatter frequency and therefore the chance of a feature trigger.",
    "When active, the engine derives a round-specific symbol table with increased Scatter weights before generating the grid. An explicit ante request also uses the configured stake multiplier for round cost.",
    "The reference explicit ante costs 1.25x the base bet unless configured otherwise.",
    "Ante Bet cannot be combined with Bonus Buy.",
    "The demo forces the Scatter-weight modifier on so its feature-start evidence is deterministic.",
  ],
  "feature-guarantee": [
    "The game forces a bonus after a configured number of consecutive rounds without a natural trigger.",
    "The engine increments a persistent miss counter whenever the normal trigger fails. At the configured limit it starts the bonus and resets the counter; a natural trigger also resets it.",
    "The reference default guarantee is five missed rounds.",
    "The demo sets the limit to one round so the forced trigger is immediately visible.",
    "The counter is stored in authoritative feature state and clears on scenario reset.",
  ],
} as const satisfies Record<string, GuideDefinition>;

export const featureGuides: Readonly<Record<string, FeatureGuide>> = Object.freeze(Object.fromEntries(
  Object.entries(definitions).map(([id, [description, howItWorks, ...rules]]) => [id, Object.freeze({ description, howItWorks, rules: Object.freeze(rules) })]),
));
