/**
 * Shared helpers for the Book of Ra integration/playtest bundle.
 *
 * Everything here is integration-only glue: it starts isolated local services,
 * talks to the accepted Nest backend over HTTP and never touches the accepted
 * UI sources, the game mathematics or another worktree.
 */
import { spawn } from 'node:child_process';
import { access, mkdir, readFile, writeFile } from 'node:fs/promises';
import { createConnection } from 'node:net';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
export const tmpDir = path.join(root, 'tmp', 'integration');
export const runDir = path.join(tmpDir, 'run');
export const logDir = path.join(tmpDir, 'logs');
export const pgDataDir = path.join(tmpDir, 'pgdata');
export const redisDataDir = path.join(tmpDir, 'redis');
export const envFile = path.join(root, '.env.integration');
export const pidFile = path.join(runDir, 'services.json');

const defaultPgBin = 'C:\\Program Files\\PostgreSQL\\18\\bin';
const defaultRedisServer = 'C:\\Program Files\\Redis\\redis-server.exe';
const defaultRedisCli = 'C:\\Program Files\\Redis\\redis-cli.exe';

export const pgBin = process.env.INTEGRATION_PG_BIN?.trim() || defaultPgBin;
export const redisServerBin = process.env.INTEGRATION_REDIS_SERVER?.trim() || defaultRedisServer;
export const redisCliBin = process.env.INTEGRATION_REDIS_CLI?.trim() || defaultRedisCli;

export const pgTool = (name) => path.join(pgBin, `${name}.exe`);

export const LOOPBACK = '127.0.0.1';

/** Windows ships npm as a .cmd shim, which `spawn` without a shell cannot run. */
export const npmBin = process.platform === 'win32' ? 'npm.cmd' : 'npm';
export const prismaEntry = path.join(root, 'node_modules', 'prisma', 'build', 'index.js');

export function log(event, detail = {}) {
  process.stdout.write(`${JSON.stringify({ event, ...detail })}\n`);
}

export function fail(message) {
  throw new Error(message);
}

export async function exists(target) {
  try {
    await access(target);
    return true;
  } catch {
    return false;
  }
}

export async function ensureDirs() {
  for (const dir of [tmpDir, runDir, logDir, redisDataDir]) {
    await mkdir(dir, { recursive: true });
  }
}

export function parseEnvFile(text) {
  const values = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const index = line.indexOf('=');
    if (index < 1) continue;
    values[line.slice(0, index).trim()] = line.slice(index + 1).trim();
  }
  return values;
}

export async function loadIntegrationEnv() {
  if (!(await exists(envFile))) {
    fail(`Missing ${path.relative(root, envFile)}. Run: node scripts/book-integration/setup.mjs`);
  }
  return parseEnvFile(await readFile(envFile, 'utf8'));
}

export function serializeEnvFile(values) {
  const lines = [
    '# Generated by scripts/book-integration/setup.mjs. Ignored by git.',
    '# Local integration/playtest configuration. Never use these values elsewhere.',
  ];
  for (const [key, value] of Object.entries(values)) lines.push(`${key}=${value}`);
  return `${lines.join('\n')}\n`;
}

export async function writeEnvFile(values) {
  await writeFile(envFile, serializeEnvFile(values), 'utf8');
}

/** Random hex token. Values are written to ignored config only, never logged. */
export function randomHex(bytes = 24) {
  const buffer = new Uint8Array(bytes);
  globalThis.crypto.getRandomValues(buffer);
  return Buffer.from(buffer).toString('hex');
}

export function randomPassword() {
  return `${randomHex(16)}-Aa1`;
}

export function run(args, { cwd = root, env = {}, log: logPath, timeoutMs = 300_000, shell = false } = {}) {
  return new Promise((resolve, reject) => {
    // With `shell` the command is passed as one string; Node warns (DEP0190)
    // when a shell is combined with a separate argument array.
    const child = spawn(shell ? args.join(' ') : args[0], shell ? [] : args.slice(1), {
      cwd,
      shell,
      windowsHide: true,
      stdio: ['ignore', 'pipe', 'pipe'],
      env: { ...process.env, ...env, NO_COLOR: '1', FORCE_COLOR: '0' },
    });
    let output = '';
    let timedOut = false;
    const timer = setTimeout(() => {
      timedOut = true;
      child.kill();
    }, timeoutMs);
    child.stdout.on('data', (chunk) => {
      output += chunk;
    });
    child.stderr.on('data', (chunk) => {
      output += chunk;
    });
    child.on('error', (error) => {
      clearTimeout(timer);
      reject(error);
    });
    child.on('close', async (code) => {
      clearTimeout(timer);
      if (logPath) {
        await mkdir(path.dirname(logPath), { recursive: true });
        await writeFile(logPath, output, 'utf8');
      }
      resolve({ code: timedOut ? 124 : (code ?? 1), output, timedOut });
    });
  });
}

/** Starts a detached hidden process and returns its pid. */
export function spawnHidden(command, args, { env = {}, log: logPath } = {}) {
  const out = logPath ?? path.join(logDir, 'process.log');
  const child = spawn(
    'powershell.exe',
    [
      '-NoProfile',
      '-NonInteractive',
      '-Command',
      `Start-Process -FilePath '${command}' -ArgumentList @(${args
        .map((value) => `'${String(value).replaceAll("'", "''")}'`)
        .join(',')}) -WindowStyle Hidden -RedirectStandardOutput '${out}' -RedirectStandardError '${out}.err'`,
    ],
    { cwd: root, windowsHide: true, env: { ...process.env, ...env }, stdio: 'ignore' },
  );
  return child;
}

export async function isPortListening(port, host = LOOPBACK, timeoutMs = 1000) {
  return new Promise((resolve) => {
    const socket = createConnection({ port, host });
    const done = (value) => {
      socket.removeAllListeners();
      socket.destroy();
      resolve(value);
    };
    socket.setTimeout(timeoutMs);
    socket.once('connect', () => done(true));
    socket.once('timeout', () => done(false));
    socket.once('error', () => done(false));
  });
}

export async function waitFor(predicate, { timeoutMs = 30_000, intervalMs = 250, label = 'condition' } = {}) {
  const deadline = Date.now() + timeoutMs;
  let lastError;
  while (Date.now() < deadline) {
    try {
      if (await predicate()) return true;
    } catch (error) {
      lastError = error;
    }
    await new Promise((resolve) => setTimeout(resolve, intervalMs));
  }
  fail(`Timed out waiting for ${label}${lastError ? `: ${lastError.message}` : ''}`);
}

export async function httpJson(url, { method = 'GET', headers = {}, body, timeoutMs = 20_000 } = {}) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetch(url, {
      method,
      headers: { ...(body === undefined ? {} : { 'content-type': 'application/json' }), ...headers },
      body: body === undefined ? undefined : JSON.stringify(body),
      signal: controller.signal,
    });
    const text = await response.text();
    let payload;
    try {
      payload = text ? JSON.parse(text) : undefined;
    } catch {
      payload = text;
    }
    return { status: response.status, ok: response.ok, payload, setCookie: response.headers.getSetCookie?.() ?? [] };
  } finally {
    clearTimeout(timer);
  }
}

export async function readPidFile() {
  if (!(await exists(pidFile))) return {};
  try {
    return JSON.parse(await readFile(pidFile, 'utf8'));
  } catch {
    return {};
  }
}

export async function writePidFile(value) {
  await mkdir(runDir, { recursive: true });
  await writeFile(pidFile, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

export function isProcessAlive(pid) {
  if (!pid) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

export function stopProcess(pid) {
  if (!isProcessAlive(pid)) return false;
  try {
    process.kill(pid);
    return true;
  } catch {
    return false;
  }
}

/** Resolves the pid listening on a loopback port, or undefined. */
export async function pidOnPort(port) {
  const result = await run(
    [
      'powershell.exe',
      '-NoProfile',
      '-NonInteractive',
      '-Command',
      `(Get-NetTCPConnection -State Listen -LocalPort ${port} -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty OwningProcess)`,
    ],
    { timeoutMs: 30_000 },
  );
  const pid = Number.parseInt(result.output.trim(), 10);
  return Number.isInteger(pid) && pid > 0 ? pid : undefined;
}

/** Command line of a pid, used to confirm a process is ours before stopping it. */
export async function processCommandLine(pid) {
  const result = await run(
    [
      'powershell.exe',
      '-NoProfile',
      '-NonInteractive',
      '-Command',
      `(Get-CimInstance Win32_Process -Filter "ProcessId = ${Number(pid)}" -ErrorAction SilentlyContinue).CommandLine`,
    ],
    { timeoutMs: 30_000 },
  );
  return result.output.trim();
}
